name: Integration Example
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Plant a Tree
        id: planttree
        uses: protontypes/continuous-reforestation@main
        with:
        # Enter your API variables below
            apikey: ${{ secrets.raaskey }}
            enterpriseid: "cd7cedcd"
            user: ${{ github.actor }}
            treecount: 10
            projectid: "92222222" # onetreeplanted.org/collections/latin-america/products/brazil-forests
            production: "true"

      - name: Response of digitalhumani.com RaaS API
        run: |
            echo "${{ steps.planttree.outputs.response }}"
