name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: protontypes/continuous-reforestation@main
        with:
            numberoftrees: 10

      - name: Check outputs
        run: |
            echo "${{ steps.selftest.outputs.myOutput }}"
